name: List surge.sh domains
on:
  workflow_dispatch:
  # Validate that the application of the patch to surge cli works
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/surge-list-domains.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  list_deployments:
    runs-on: ${{ vars.RUNNER_UBUNTU }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Install the patch of the surge cli
        uses: bahmutov/npm-install@v1
        with:
          # do not set --ignore-scripts as we patch "surge" with a script
          install-command: npm ci --prefer-offline --audit false
      - name: List deployments
        run: |
          npx surge --token ${{ secrets.SURGE_TOKEN }} list
